### ISSUE TITLE
Bloopair only detects for dualshock 3 controllers

### ISSUE THREAD

**Issue by hey111543** [GaryOderNichts/Bloopair#122]
In your description of the app it states you can connect other controllers, but in the app it says it only detects dualshock 3 controllers

**Comment by GaryOderNichts** [comment]
That's because the "DS3 Pairing Menu" is only required for pairing the Dualshock 3 to the console and is otherwise not necessary for Bloopair to function.
All other controllers don't need an additional app while Bloopair is running and can be paired through the Wii U menu as mentioned in the README.

**Comment by hey111543** [comment]
oh thanks
