### ISSUE TITLE
Hang on Wii u menu loading after n64

### ISSUE THREAD

**Issue by Bolexle** [GaryOderNichts/Bloopair#17]
I have found a reproducible bug, at least on my Wii u. I use cbhx and whenever I launch an injected N64 game, the game runs fine, but if I use home and close the software, my console hangs at the Wii u home menu screen. (Music still plays so not hard crashed, just stuck loading.) This only happens when I have Bloopair enabled, I cannot get it to happen using regular Wii u controllers or with HID to Vpad.

Is there a way for me to export some sort of debug to help you? I'd love to get this fixed as I love using my Xbox controller for retro games.

**Comment by Bolexle** [comment]
To clarify I have tried both version 0.1 and 0.2, both behave the same.

**Comment by kazcio** [comment]
I was able to reproduce this issue too, I am running haxchi cfw. The workflow to reproduce:
Run haxchi, run homebrew channel, run bloopair, run injected SNES game, game is running fine, try to close it down, you will get the Wii u menu with background music stuck forever. Without bloopair issue is not present.

**Comment by GaryOderNichts** [comment]
This doesn't seem to be an issue with Bloopair.
This can be reproduced with any app launched from the Homebrew Launcher Channel.
To reproduce:
`Launch the Homebrew Launcher Channel -> Launch any .rpx -> Exit back to the Wii U menu -> Launch any VC game and exit from it`
There is nothing I can do about that, since that's an issue with the HBLC.
As a workaround, launch Bloopair from the browser exploit or from haxchis HBL, which doesn't seem to have this issue.
You could also create a channel from the .rpx.

I'm not sure if it's worth looking into this, if aroma is released Bloopair will probably be a module anyways.

**Comment by Bolexle** [comment]
Ah gotcha, makes sense. Thanks for the update! I hadn't thought to try other .rpx files.
