### ISSUE TITLE
Wii U freeze

### ISSUE THREAD

**Issue by BaamAlex** [GaryOderNichts/Bloopair#38]
The program works perfectly. But sometimes the console freezes when i leave the system settings or close a game. It stucks in the "Wii U Menu" screen forever. Just holding the power button can shut down the console.

**Comment by GaryOderNichts** [comment]
Are you using the Homebrew Launcher Channel to launch Bloopair?
There seems to be an issue with the Homebrew Launcher Channel. This isn't something that can be fixed in Bloopair itself.
See the following [issue comment](https://github.com/GaryOderNichts/Bloopair/issues/17#issuecomment-932974462) for more info.

**Comment by BaamAlex** [comment]
I use a channel from a user from GBATemp.

**Comment by GaryOderNichts** [comment]
That channel might contain the same bug the Homebrew Launcher Channel does. Does launching Bloopair from the normal Homebrew Launcher have the same freezes?

**Comment by GaryOderNichts** [comment]
This should be no longer relevant with the Tiramisu version.
